server:
  #端口
  port: 8076
  servlet:
  context-path: /
#--------------------------------------------------------------------------------------------------#
spring:
  application:
    #consul里的名字，也可以在bootstarp.yml里配置
    name: ceshi
#--------------------------------------------------------------------------------------------------#
